"""Add DealAttachment model

Revision ID: 503c41657937
Revises: fc9218edad03
Create Date: 2025-04-23 16:51:44.943320

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '503c41657937'
down_revision = 'fc9218edad03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deal_attachment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('filepath', sa.String(length=512), nullable=False),
    sa.Column('file_type', sa.Enum('MANUFACTURER_QUOTE', 'CUSTOMER_QUOTE', 'CUSTOMER_PO', 'EVT_PO', name='attachmenttype'), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('deal_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['deal_id'], ['deal.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('deal_attachment')
    # ### end Alembic commands ###
