"""Add first_name and last_name to User model

Revision ID: 682806a9cbfe
Revises: 95e1c9a161f9
Create Date: 2025-04-30 15:57:42.977768

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '682806a9cbfe'
down_revision = '95e1c9a161f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('last_name', sa.String(length=100), nullable=True))
        batch_op.drop_constraint('uq_user_email', type_='unique')
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_email'))
        batch_op.create_unique_constraint('uq_user_email', ['email'])
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')

    # ### end Alembic commands ###
