"""Add SOW to AttachmentType enum

Revision ID: 95e1c9a161f9
Revises: 27fc2a923d5f
Create Date: 2025-04-24 12:37:08.382473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95e1c9a161f9'
down_revision = '27fc2a923d5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE attachmenttype ADD VALUE 'SOW'")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Removing enum values can be complex and might require data migration.
    # For now, we'll just pass, assuming rollback isn't strictly needed or 
    # will be handled manually if required.
    pass
    # ### end Alembic commands ###
