"""Add role to User model

Revision ID: aa594708dc30
Revises: b309f18fe4c7
Create Date: 2025-04-11 12:12:45.745602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa594708dc30'
down_revision = 'b309f18fe4c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Step 1: Add the column, allowing NULLs initially
    op.add_column('user', sa.Column('role', sa.String(length=20), nullable=True))

    # Step 2: Update existing rows to have the default role 'member'
    # Use execute for data manipulation; ensure table/column names are quoted if needed
    op.execute("UPDATE \"user\" SET role='member' WHERE role IS NULL")

    # Step 3: Alter the column to be NOT NULL and create the index within a batch operation
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.String(length=20),
               nullable=False) # Make non-nullable
        batch_op.create_index(batch_op.f('ix_user_role'), ['role'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_role'))
        batch_op.drop_column('role')

    # ### end Alembic commands ###
