"""Add contact name and email to Deal model

Revision ID: fc9218edad03
Revises: aa594708dc30
Create Date: 2025-04-11 12:39:18.969783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc9218edad03'
down_revision = 'aa594708dc30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contact_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('contact_email', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deal', schema=None) as batch_op:
        batch_op.drop_column('contact_email')
        batch_op.drop_column('contact_name')

    # ### end Alembic commands ###
